version: '3'

vars:
  BINARY_NAME: messh

tasks:
  default:
    desc: Run the default task
    cmds:
      - task --list-all

  build:
    desc: Build the binary
    cmds:
      - go build -ldflags="-s -w" -o {{.BINARY_NAME}}.exe ./src/main.go

  tidy:
    desc: Tidy the project
    cmds:
      - go mod tidy
      - go mod verify